In [34]:
# b
import numpy as np
import math
# N > d+1
X = [[2,4,6],[1,3,5],[1,4,7],[3,5,7]]
X = np.asarray(X)
X_cross = np.linalg.pinv(X)
XX_cross = np.dot(X,X_cross)
# k = 2,4
XX_cross_2 = np.dot(XX_cross, XX_cross)
XX_cross_4 = np.dot(XX_cross_2, XX_cross_2)
print(XX_cross)
print(XX_cross_2)
print(XX_cross_4)

[[ 0.26666667  0.13333333  0.13333333  0.4       ]
 [ 0.13333333  0.23333333  0.4         0.03333333]
 [ 0.13333333  0.4         0.73333333 -0.13333333]
 [ 0.4         0.03333333 -0.13333333  0.76666667]]
[[ 0.26666667  0.13333333  0.13333333  0.4       ]
 [ 0.13333333  0.23333333  0.4         0.03333333]
 [ 0.13333333  0.4         0.73333333 -0.13333333]
 [ 0.4         0.03333333 -0.13333333  0.76666667]]
[[ 0.26666667  0.13333333  0.13333333  0.4       ]
 [ 0.13333333  0.23333333  0.4         0.03333333]
 [ 0.13333333  0.4         0.73333333 -0.13333333]
 [ 0.4         0.03333333 -0.13333333  0.76666667]]


In [21]:
# c
import numpy as np
# N > d+1
X = [[2,4,6],[1,3,5],[1,4,7],[3,5,7]]
X = np.asarray(X)
X_cross = np.linalg.pinv(X)
np.dot(X,X_cross)

array([[ 0.26666667,  0.13333333,  0.13333333,  0.4       ],
       [ 0.13333333,  0.23333333,  0.4       ,  0.03333333],
       [ 0.13333333,  0.4       ,  0.73333333, -0.13333333],
       [ 0.4       ,  0.03333333, -0.13333333,  0.76666667]])

In [37]:
# d
import numpy as np
# N > d+1
X = [[2,4,6],[1,3,5],[1,4,2],[3,5,2]]
X = np.asarray(X)
X_cross = np.linalg.pinv(X)
XX_cross = np.dot(X,X_cross)
trace = np.trace(XX_cross)
rank = np.linalg.matrix_rank(X)

print("trace: ",trace)
print("rank: ",rank)

trace:  3.000000000000001
rank:  3
